# Generated by Django 2.0.7 on 2019-07-29 15:56

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Generic', help_text='Enter the category of the item', max_length=50, validators=[inventory.models.validate_single_word])),
                ('extra_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField(help_text='Enter the floor number')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic', help_text='Enter the brand name of the item', max_length=50)),
                ('model', models.CharField(blank=True, default='Generic', help_text='Enter the model of the item', max_length=50, null=True)),
                ('cost_per_item', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the cost per item', max_digits=10, null=True)),
                ('date_of_acquire', models.DateField(default=datetime.date.today, help_text='Enter the date of acquire')),
                ('working', models.IntegerField(default=0)),
                ('in_maintenance', models.IntegerField(default=0)),
                ('out_of_order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('extra_value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('category', models.ForeignKey(help_text='Select the category of the equipment', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.PositiveSmallIntegerField(help_text='Enter the room number')),
                ('room_name', models.CharField(default='Generic', help_text='Enter the name of the room', max_length=50)),
                ('floor', models.ForeignKey(help_text='In which floor is this room?', on_delete=django.db.models.deletion.CASCADE, to='inventory.Floor')),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic', help_text='Enter the name of the sub-item', max_length=50)),
                ('model', models.CharField(blank=True, default='Generic', help_text='Enter the model of the sub-item', max_length=50, null=True)),
                ('cost_per_item', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the cost per sub-item', max_digits=10, null=True)),
                ('working', models.IntegerField(default=0)),
                ('in_maintenance', models.IntegerField(default=0)),
                ('out_of_order', models.IntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='inventory.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='room',
            field=models.ForeignKey(help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
    ]
