# Generated by Django 2.0.7 on 2019-07-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190314_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, default='Generic', help_text='Enter the model of the item', max_length=50, null=True),
        ),
    ]
