# Generated by Django 2.0.7 on 2019-07-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190726_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='Generic', help_text='Enter the name of the room', max_length=50),
        ),
    ]
