# Generated by Django 2.0.7 on 2019-07-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190726_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the cost per item', max_digits=10, null=True),
        ),
    ]
