# Generated by Django 2.0.7 on 2019-07-26 02:30

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190726_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Select the category of the equipment', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Categorie', validators=[inventory.models.validate_single_word]),
        ),
    ]
