# Generated by Django 2.0.7 on 2019-07-26 02:31

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20190726_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='category_name',
            field=models.CharField(default='Generic', help_text='Enter the category of the item', max_length=50, validators=[inventory.models.validate_single_word]),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Select the category of the equipment', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Categorie'),
        ),
    ]
